name: Publish Documentation
on:
  push:
    branches:
      - master

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
          cache: 'pip'

      - name: Install MkDocs
        run: pip install -r requirements.txt

      - name: Build MkDocs (outputs to site/)
        run: mkdocs build

      - name: Generate Javadocs (outputs to build/docs/javadoc)
        run: ./gradlew :javadoc

      - name: Move Javadocs into MkDocs site
        run: |
          mkdir -p site/javadoc
          cp -a build/docs/javadoc/. site/javadoc/

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './site'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
